//! QUIC transport implementation using `quinn`.
//!
//! QUIC provides:
//! - 0-RTT connection establishment (eliminates TCP 3-way handshake)
//! - Multiplexed streams (no head-of-line blocking)
//! - Built-in TLS 1.3 (encryption at wire speed)
//! - Connection migration (survives IP changes)

use super::{mtu_payload_floats, NetError, Transport};
use crate::protocol::{decode_header, HEADER_SIZE, MAX_PAYLOAD_FLOATS};
use std::net::SocketAddr;
use std::sync::Arc;

/// QUIC-backed transport for Akasha P2P tensor relay.
pub struct QuicTransport {
    endpoint: Option<quinn::Endpoint>,
    connection: Option<quinn::Connection>,
    send_stream: Option<quinn::SendStream>,
    recv_stream: Option<quinn::RecvStream>,
    connected: bool,
    /// Pre-allocated receive buffer (HEADER_SIZE + max datagram payload).
    recv_buf: Box<[u8]>,
}

impl QuicTransport {
    /// Create a new QUIC transport.
    ///
    /// The endpoint is lazily created on `connect()` because the local
    /// bind address may not be known until the platform layer resolves it.
    pub fn new() -> Self {
        let recv_size = HEADER_SIZE + mtu_payload_floats() * 4;
        Self {
            endpoint: None,
            connection: None,
            send_stream: None,
            recv_stream: None,
            connected: false,
            recv_buf: vec![0u8; recv_size].into_boxed_slice(),
        }
    }

    /// Configure TLS for the QUIC endpoint.
    fn configure_tls() -> Result<quinn::ClientConfig, NetError> {
        // In production, the master's certificate would be pinned.
        // For development, we use a self-signed cert generated by rcgen.
        let mut roots = rustls::RootCertStore::empty();

        // Use a simple self-signed cert for development.
        // Production: load the master's CA cert from a known path.
        let cert = rcgen::generate_simple_self_signed(vec!["akasha.local".into()])
            .map_err(|e| NetError::Protocol(format!("cert gen: {e}")))?;
        roots
            .add(cert.cert.der().clone())
            .map_err(|e| NetError::Protocol(format!("add cert: {e}")))?;

        let tls_config = rustls::ClientConfig::builder()
            .with_root_certificates(roots)
            .with_no_client_auth();

        let mut transport = quinn::TransportConfig::default();
        // Maximise throughput for tensor data
        transport
            .max_concurrent_bidi_streams(1u32.into())
            .send_window(16 * 1024 * 1024)
            .receive_window(quinn::VarInt::from_u64(16 * 1024 * 1024).unwrap()); // 16 MiB recv window

        // quinn 0.11: wrap rustls config in QuicClientConfig
        let quic_crypto = quinn::crypto::rustls::QuicClientConfig::try_from(tls_config)
            .map_err(|e| NetError::Protocol(format!("quic tls: {e}")))?;
        let mut config = quinn::ClientConfig::new(Arc::new(quic_crypto));
        config.transport_config(Arc::new(transport));

        Ok(config)
    }
}

#[async_trait::async_trait]
impl Transport for QuicTransport {
    async fn connect(&mut self, addr: SocketAddr) -> Result<(), NetError> {
        // Bind to any available local port
        let bind_addr: SocketAddr = "0.0.0.0:0".parse().unwrap();
        let mut endpoint = quinn::Endpoint::client(bind_addr)
            .map_err(|e| NetError::Protocol(format!("endpoint: {e}")))?;

        let config = Self::configure_tls()?;

        // quinn 0.11: connect_with(config, addr, server_name)
        let connecting = endpoint
            .connect_with(config, addr, "akasha.local")
            .map_err(|e| NetError::ConnectionRefused(format!("connect: {e}")))?;

        let connection = connecting
            .await
            .map_err(|e| NetError::ConnectionRefused(format!("handshake: {e}")))?;

        let (send, recv) = connection
            .open_bi()
            .await
            .map_err(|e| NetError::ConnectionRefused(format!("open stream: {e}")))?;

        self.endpoint = Some(endpoint);
        self.connection = Some(connection);
        self.send_stream = Some(send);
        self.recv_stream = Some(recv);
        self.connected = true;

        log::info!("QUIC connected to {}", addr);
        Ok(())
    }

    async fn send(&mut self, frame: &[u8]) -> Result<(), NetError> {
        let send = self
            .send_stream
            .as_mut()
            .ok_or(NetError::ConnectionClosed)?;

        // Write frame length prefix (u32 LE) + frame data
        let len_prefix = (frame.len() as u32).to_le_bytes();
        send.write_all(&len_prefix).await.map_err(|e| NetError::Protocol(format!("quic send: {e}")))?;
        send.write_all(frame).await.map_err(|e| NetError::Protocol(format!("quic send: {e}")))?;

        Ok(())
    }

    async fn recv(&mut self, buf: &mut [u8]) -> Result<usize, NetError> {
        let recv = self
            .recv_stream
            .as_mut()
            .ok_or(NetError::ConnectionClosed)?;

        // Read length prefix
        let mut len_buf = [0u8; 4];
        recv.read_exact(&mut len_buf).await?;
        let frame_len = u32::from_le_bytes(len_buf) as usize;

        if frame_len > buf.len() {
            return Err(NetError::Protocol(format!(
                "frame too large: {frame_len} > {}",
                buf.len()
            )));
        }

        recv.read_exact(&mut buf[..frame_len]).await?;
        Ok(frame_len)
    }

    async fn close(&mut self) -> Result<(), NetError> {
        self.connected = false;
        if let Some(conn) = self.connection.take() {
            conn.close(0u32.into(), b"kernel-shutdown");
        }
        if let Some(endpoint) = self.endpoint.take() {
            endpoint.close(0u32.into(), b"kernel-shutdown");
        }
        Ok(())
    }

    fn is_connected(&self) -> bool {
        self.connected
    }
}

// ─── Convenience: receive a full Akasha packet ─────────────────────────────

impl QuicTransport {
    /// Receive one complete Akasha binary packet (header + payload).
    ///
    /// On success, returns `(header, payload_floats_slice)`.
    /// The payload slice borrows from `recv_buf` and is valid until the
    /// next `recv_packet` call.
    pub async fn recv_packet<'a>(
        &'a mut self,
    ) -> Result<
        (
            crate::protocol::PacketHeader,
            &'a [f32],
        ),
        NetError,
    > {
        // recv_buf を先に mutable 借用として分離し、recv() には recv_stream だけ渡す
        let n = {
            let recv: &mut quinn::RecvStream = self
                .recv_stream
                .as_mut()
                .ok_or(NetError::ConnectionClosed)?;
            let buf = &mut self.recv_buf;
            // 長さプレフィックスを読む
            let mut len_buf = [0u8; 4];
            recv.read_exact(&mut len_buf).await?;
            let frame_len = u32::from_le_bytes(len_buf) as usize;
            if frame_len > buf.len() {
                return Err(NetError::Protocol(format!(
                    "frame too large: {frame_len} > {}",
                    buf.len()
                )));
            }
            recv.read_exact(&mut buf[..frame_len]).await?;
            frame_len
        };
        let header = decode_header(&self.recv_buf[..n])
            .ok_or(NetError::Protocol("bad packet header".into()))?;

        let payload =
            crate::protocol::payload_as_floats(&self.recv_buf[..n], header.payload_len);

        Ok((header, payload))
    }
}
