/**
 * Native Harness（H1）— 既存 Coding の決定論的ロジックを閉じ込める。
 *
 * CodingAttachment
 *      ↓
 *   Harness（ABI）
 *      ↓
 * NativeHarness
 *      ↓
 * existing coding logic（コード生成 → 自己レビュー → node --check 実コンパイル）
 *
 * 目的: DeepSeek Harness なしで ABI を検証する。
 */
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type { Harness } from './harness.js';
import type { HarnessEvent } from './events.js';
import type { HarnessTask, HarnessExecuteOptions } from './types.js';
import { HarnessInfrastructureError } from './types.js';

const execFileAsync = promisify(execFile);

/** タスク文から関数名を推定（決定論） */
export function suggestFunctionName(text: string): string {
  const cleaned = text.replace(/[^a-zA-Z0-9\u3040-\u30ff\u4e00-\u9fff]/g, ' ').trim();
  const words = cleaned.split(/\s+/).filter((w) => w.length > 0).slice(-2);
  const latin = words.filter((w) => /^[a-zA-Z]/.test(w)).join('');
  return latin && /^[a-zA-Z]/.test(latin) ? latin : 'solve';
}

/** 生成する JS コード（実コンパイル対象） */
export function generateCode(text: string): string {
  const fn = suggestFunctionName(text);
  return [
    `/**`,
    ` * Generated by ArcAsha Coding Harness (Native)`,
    ` * Task: ${text}`,
    ` */`,
    `export function ${fn}(input) {`,
    `  // TODO: implement ${text}`,
    `  return input;`,
    `}`,
    ``,
  ].join('\n');
}

/**
 * 実際に Node で構文チェック（node --check）。成功なら実コンパイル OK。
 * 一時ファイルに書き出して検証する（検証後は削除）。AbortSignal を伝播する。
 */
async function compileCheck(code: string, signal?: AbortSignal): Promise<{ ok: boolean; output: string }> {
  const os = await import('node:os');
  const fs = await import('node:fs');
  const path = await import('node:path');
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'arcasha-code-'));
  const file = path.join(tmpDir, 'generated.mjs');
  fs.writeFileSync(file, code, 'utf-8');
  try {
    await execFileAsync(process.execPath, ['--check', file], { timeout: 15000, signal });
    return { ok: true, output: 'syntax OK' };
  } catch (e) {
    if (signal?.aborted) {
      throw new HarnessInfrastructureError('aborted during compilation');
    }
    const err = e as { stderr?: string; message?: string };
    return { ok: false, output: (err.stderr ?? err.message ?? String(e)).slice(0, 300) };
  } finally {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
  }
}

/**
 * Native Harness — 決定論的コード生成 + 実コンパイル検証。
 * 成功: started → completed(result)
 * 失敗（コンパイル不可）: started → failed(error)
 * 継続不能: started → throw（HarnessInfrastructureError）
 */
export class NativeHarness implements Harness {
  async *execute(task: HarnessTask, options?: HarnessExecuteOptions): AsyncIterable<HarnessEvent> {
    const executionId = `native-${task.taskId}-${Date.now()}`;
    yield { type: 'started', taskId: task.taskId, executionId, timestamp: Date.now() };

    if (options?.signal?.aborted) {
      throw new HarnessInfrastructureError('aborted before execution');
    }

    let code: string;
    let attempts: number;
    let compile: { ok: boolean; output: string };
    try {
      code = generateCode(task.text);
      attempts = 1;
      compile = await compileCheck(code, options?.signal);
      if (!compile.ok) {
        // 1回目失敗 → コメント除去で修正 → リトライ
        code = generateCode(task.text).replace(/\/\*\*[\s\S]*?\*\//g, '').replace(/^\s*$/gm, '').trim() + '\n';
        attempts = 2;
        compile = await compileCheck(code, options?.signal);
      }
    } catch (e) {
      if (e instanceof HarnessInfrastructureError) throw e;
      throw new HarnessInfrastructureError(`NativeHarness 実行失敗: ${(e as Error).message}`);
    }

    if (compile.ok) {
      yield {
        type: 'completed',
        taskId: task.taskId,
        executionId,
        result: {
          ok: true,
          output: code,
          metadata: { attempts, functionName: suggestFunctionName(task.text) },
        },
        timestamp: Date.now(),
      };
    } else {
      yield {
        type: 'failed',
        taskId: task.taskId,
        executionId,
        error: { code: 'COMPILE_FAIL', message: compile.output, retryable: true },
        timestamp: Date.now(),
      };
    }
  }
}
